In [22]:
#Import libraries
import numpy as np

In [23]:
#Initialize data
node_value_data = np.genfromtxt("data.csv", delimiter="\t")
nodes = node_value_data.shape[0]
node_value_data

array([[nan, 10., nan, nan, nan,  7., nan, nan, nan, nan, nan, nan, nan,
         3., nan, nan],
       [10., nan,  8., nan,  3., nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan],
       [nan,  8., nan,  7., nan, nan, nan,  1.,  3., nan, nan, nan, nan,
        nan, nan, nan],
       [nan, nan,  7., nan, nan, nan, nan, nan,  4.,  2., nan, nan, nan,
        nan, nan, nan],
       [nan,  3., nan, nan, nan,  2.,  2.,  4., nan, nan, nan,  8., nan,
        nan,  9., nan],
       [ 7., nan, nan, nan,  2., nan, nan, nan, nan, nan, nan, nan,  2.,
        nan, nan, nan],
       [nan, nan, nan, nan,  2., nan, nan, nan, nan, nan, nan, nan, nan,
        24., nan, nan],
       [nan, nan,  1., nan,  4., nan, nan, nan,  9., nan, nan,  2., nan,
        nan, nan, nan],
       [nan, nan,  3.,  4., nan, nan, nan,  9., nan,  2.,  7., nan, nan,
        nan, nan, nan],
       [nan, nan, nan,  2., nan, nan, nan, nan, nan, nan, 12., nan, nan,
        nan, nan, nan],
       [nan, nan, nan, nan, na

In [24]:
#Remove unknown value with Infinity
node_value_data[np.isnan(node_value_data)]  = np.Infinity
node_value_data

array([[inf, 10., inf, inf, inf,  7., inf, inf, inf, inf, inf, inf, inf,
         3., inf, inf],
       [10., inf,  8., inf,  3., inf, inf, inf, inf, inf, inf, inf, inf,
        inf, inf, inf],
       [inf,  8., inf,  7., inf, inf, inf,  1.,  3., inf, inf, inf, inf,
        inf, inf, inf],
       [inf, inf,  7., inf, inf, inf, inf, inf,  4.,  2., inf, inf, inf,
        inf, inf, inf],
       [inf,  3., inf, inf, inf,  2.,  2.,  4., inf, inf, inf,  8., inf,
        inf,  9., inf],
       [ 7., inf, inf, inf,  2., inf, inf, inf, inf, inf, inf, inf,  2.,
        inf, inf, inf],
       [inf, inf, inf, inf,  2., inf, inf, inf, inf, inf, inf, inf, inf,
        24., inf, inf],
       [inf, inf,  1., inf,  4., inf, inf, inf,  9., inf, inf,  2., inf,
        inf, inf, inf],
       [inf, inf,  3.,  4., inf, inf, inf,  9., inf,  2.,  7., inf, inf,
        inf, inf, inf],
       [inf, inf, inf,  2., inf, inf, inf, inf, inf, inf, 12., inf, inf,
        inf, inf, inf],
       [inf, inf, inf, inf, in

In [25]:
#Initialize nodes and output matrix
unvisited = [i for i in range(nodes)]
output = np.empty((0,3),int)

In [26]:
'''
Input: source and destination
output: array of shortest path
'''
def findShortestPath(source,destination):
    global node_value_data,nodes,unvisited,visited,output
    
    for i in range(nodes):
        if i == source:
            output = np.vstack((output, np.array([i,0,0])))
        else:
            output = np.vstack((output, np.array([i,np.Infinity,-1])))
            
    while len(unvisited) != 0:
        min = np.Infinity
        current_node = np.Infinity
        
        for i in unvisited:
            if output[:,1][i] < min:
                min = output[:,1][i]
                current_node = i

        unvisited.remove(current_node)
        
        current_node_value = node_value_data[current_node]
        for i in range(nodes):
            if i in unvisited and current_node_value[i] != np.inf:
                if output[:,1][i] > (min+current_node_value[i]):
                    output[:,1][i] = min+current_node_value[i]
                    output[:,2][i] = current_node
    
    path = np.array([])
    i = destination                    
    while i != source:
        path = np.append(path,[i])
        i = int(output[:,2][i])
    path = np.append(path,[source])
    
    return np.flip(path)

In [27]:
findShortestPath(0,10)

array([ 0.,  5.,  4.,  7.,  2.,  8., 10.])

In [ ]:
sns.